openapi: 3.0.1
info:
  title: Документация по API сервиса pickup-point
  description: Описание API сервиса pickup-point
  contact:
    email: no-reply@liga.ru
  version: 0.1.0
tags:
  - name: PickupPoint
    description: Пункт выдачи заказа

components:
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
security:
  - bearerAuth: [ ]

paths:
  # Поиск всех пунктов выдачи
  /v1/pickup-points/list:
    get:
      tags:
        - PickupPoint
      operationId: getPickupPoints
      description: Поиск всех пунктов выдачи
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './definitions/request-data.yaml#/GetAllPickupPointsResponse'
