openapi: 3.0.1
info:
  title: Документация по API сервиса products
  description: Описание API сервиса products
  contact:
    email: no-reply@liga.ru
  version: 0.1.0
tags:
  - name: Products
    description: Получение товаров

components:
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
security:
  - bearerAuth: [ ]

paths:
  # Получение всех продуктов
  /v1/products/all:
    get:
      tags:
        - Product
      operationId: getAllProducts
      description: Получение всех остатков товаров
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './definitions/request-data.yaml#/GetAllProductsResponse'